### ISSUE TITLE
Name less self user

### ISSUE THREAD

**Issue by Angel-V-Rivera** [ElBowSpace/ElBowSpaceProject#105]
If a user creates a profile without providing a first and last name the user won't be able to see its own profile. Although other users will be able to see the profile from that user.

**Comment by KevinBRitter** [comment]
model changed to prevent optional first / last name.  Now required and the usage on the site is limited to unique username

**Comment by KevinBRitter** [comment]
This has been fixed.  Users are required to enter first and last names during sign up. Updated on site with M-7 2.0 update.
