### ISSUE TITLE
Username doesn't show up on post.

### ISSUE THREAD

**Issue by chogue1** [ElBowSpace/ElBowSpaceProject#108]
Username doesn't show up on post. Only the optional first and last name shows up.

**Comment by KevinBRitter** [comment]
Thank you for your feedback.  We have prioritized this issue and are working to resolve it before the next release.

Duplicate Issue: [Name less self user #105](https://github.com/ElBowSpace/ElBowSpaceProject/issues/105)

**Comment by KevinBRitter** [comment]
Fixed. Updated on site with M-7 2.0 update.
