### ISSUE TITLE
Issue with user list, account name

### ISSUE THREAD

**Issue by maknop** [ElBowSpace/ElBowSpaceProject#109]
Once I sign-in my name was not added to the user list. Additionally, I did give an account name which did not show up on my post.

**Comment by KevinBRitter** [comment]
Thank you for your feedback.  We have prioritized this issue and are working to resolve it before the next release.

Duplicate Issue: [Name less self user #105](https://github.com/ElBowSpace/ElBowSpaceProject/issues/105)

**Comment by KevinBRitter** [comment]
Fixed. Updated on site with M-7 2.0 update.
