### ISSUE TITLE
Contents Table/Website Format

### ISSUE THREAD

**Issue by thom1664** [ElBowSpace/ElBowSpaceProject#110]
Overall great work! The application is very easy to navigate as a new user and your model looks exceptional. I'd recommend moving the contents table up to the top of every page so you don't have to scroll down as much (for example in the User Guide tab). I'd also recommend using a bootstrap template to make the sign up page a little cleaner but otherwise awesome work guys!

**Comment by KevinBRitter** [comment]
Thank you for your feedback. We have this in our backlog already but we do appreciate all constructive criticism like this.

Duplicate issue: [Nav-bar sliding down on long lists #104](https://github.com/ElBowSpace/ElBowSpaceProject/issues/104)

**Comment by KevinBRitter** [comment]
Fixed. Updated on site with M-7 2.0 update. The former side-bar has been replaced with a new nav-bar that is sticky to the top of the page.  It currently scrolls up after a full page of replies or users have been scrolled past, but it is now in an easy to find location.
