### ISSUE TITLE
only uses name for post author

### ISSUE THREAD

**Issue by KiraMatchBox** [ElBowSpace/ElBowSpaceProject#111]
If you create an account without filling in your name it leaves the post author blank when you make a post. It might be good to have it so that in this case it uses the account user name as the post author. 
Overall looks really good guys. Well done

**Comment by KevinBRitter** [comment]
Thank you for your feedback.  We have prioritized this issue and are working to resolve it before the next release.

Duplicate Issue: [Name less self user #105](https://github.com/ElBowSpace/ElBowSpaceProject/issues/105)

**Comment by KevinBRitter** [comment]
First, Last name credit on post has been changed to username for release 2.0 this weekend.

**Comment by KevinBRitter** [comment]
Fixed. Updated on site with M-7 2.0 update.
