### ISSUE TITLE
Not super urgent buut..

### ISSUE THREAD

**Issue by torr3271** [ElBowSpace/ElBowSpaceProject#112]
The spacing of the "feed" looks a little off and feels plain. Although I do like that new posts come to the top instead of having to scroll to the bottom.

**Comment by KevinBRitter** [comment]
Thank you for your feedback.  Our site polish is a priority for the next version release.  As we aspire to be great engineers we have embraced the mantra "Function Over Form."  If the site works, then we can make it pretty.  We are getting to that point now.

**Comment by KevinBRitter** [comment]
Updated on site with M-7 2.0 update.  In addition to major/ minor bug fixes we changed the style of the site.  Its not perfect but we think it is much improved.  We have prioritized user experience going forward.
