### ISSUE TITLE
Contents Menu

### ISSUE THREAD

**Issue by ramosv** [ElBowSpace/ElBowSpaceProject#113]
Great job you all, the functionality of the website is great and connections feature is pretty cool. I noticed that the contents menu gets pushed down with each post, it looks like it just sits at the middle of all the posts. I am not sure if this is how it was designed to be but I thought I'd mentioned it.

**Comment by KevinBRitter** [comment]
Thank you for your feedback.  We have this in our backlog already but we do appreciate all constructive criticism like this.

Duplicate issue: [Nav-bar sliding down on long lists #104](https://github.com/ElBowSpace/ElBowSpaceProject/issues/104)

**Comment by KevinBRitter** [comment]
Fixed. Updated on site with M-7 2.0 update. Former Side-Bar changed to Nav-Bar.  It stays at the top.
