### ISSUE TITLE
Great Job!

### ISSUE THREAD

**Issue by hart2533** [ElBowSpace/ElBowSpaceProject#117]
One issue I thought of was there is no easy way to get back to previous pages on the actual web page. The user has to use the back arrow located on the main browser. Another issue, replying to specific posts is sent to the global feed and doesn't show the relationship between the first post and the post that was a reply to the first post.

**Comment by KevinBRitter** [comment]
Thank you for your feedback.  The team is working on a new feature that allows replies to be connected directly to the post they are related to. Duplicate issue [Post_replies on Post_Detail #102](https://github.com/ElBowSpace/ElBowSpaceProject/issues/102)

**Comment by KevinBRitter** [comment]
Fixed. Updated on site with M-7 2.0 update.  Post replies now appear below the post being replied to on that posts detail page.  There are still restrictions on post_list and user_detail pages regarding replies but those will be refined in future updates.
