### ISSUE TITLE
Blank Users

### ISSUE THREAD

**Issue by schroederjacob** [ElBowSpace/ElBowSpaceProject#119]
Good work on the website, but I've noticed that the user list has a lot of blank spaces with no names.

**Comment by KevinBRitter** [comment]
Thank you for your feedback.  This is a duplicate issue that has been solved for the next build.  We are working to update the live site with the 2.0 changes.  Look for this in the coming days.

Duplicate Issue: [Name less self user #105](https://github.com/ElBowSpace/ElBowSpaceProject/issues/105)

**Comment by KevinBRitter** [comment]
Fixed. Updated on site with M-7 2.0 update.
