### ISSUE TITLE
Message Replies

### ISSUE THREAD

**Issue by ewhalenkamp** [ElBowSpace/ElBowSpaceProject#120]
I noticed when leaving a reply to another message, my message was listed in the general list of posts. This is all well and good, but the only link to it being a reply of another post was the original post id being listed after clicking on my post. For navigation's sake, it's a little bit troublesome having to comb through the general post list looking for the correct post under the proper id. There's a few ways to go about making this a bit easier, but I'll leave that to you. Cool site!

**Comment by KevinBRitter** [comment]
Thank you for your feedback.  The team is working on a new feature that allows replies to be connected directly to the post they are related to. Duplicate issue [Post_replies on Post_Detail #102](https://github.com/ElBowSpace/ElBowSpaceProject/issues/102)

**Comment by KevinBRitter** [comment]
Fixed. Updated on site with M-7 2.0 update.  We added a handy link to each post if it is a reply to a previous post you can follow the link.  In addition all replies to a post will appear under it in that posts detail page.  We will make further refinements in a future update.
