### ISSUE TITLE
Create New User Testing Plan

### ISSUE THREAD

**Issue by KevinBRitter** [ElBowSpace/ElBowSpaceProject#21]
Reference the appropriate wire frame to create a testing plan for the new user page.  Coordinate with the code team to define expectations for a successful testing suite.

Design team's wireframes for milestone 2 are in the [artifacts](https://github.com/ElBowSpace/ElBowSpaceProject/tree/master/docs/artifacts/wireframes_and_flowcharts/milestone-2) folder

**Comment by KevinBRitter** [comment]
Low priority on milestone 2, re-evaluate for milestone 3

**Comment by KevinBRitter** [comment]
This required successful creation and integration of forms model code.  We can now generate the tests necessary for new user, aka register page.

**Comment by bdmcewen** [comment]
tests created for user creation
