### ISSUE TITLE
Create User Login Testing Plan

### ISSUE THREAD

**Issue by KevinBRitter** [ElBowSpace/ElBowSpaceProject#22]
Reference the appropriate wire frame to create a testing plan for the user login page.  Coordinate with the code team to define expectations for a successful testing suite.

Design team's wireframes for milestone 2 are in the [artifacts](https://github.com/ElBowSpace/ElBowSpaceProject/tree/master/docs/artifacts/wireframes_and_flowcharts/milestone-2) folder

**Comment by KevinBRitter** [comment]
Low priority for milestone 2, re-evaluate for milestone 3

**Comment by KevinBRitter** [comment]
This functional test required the creation and integration of form models for login.  That background work is done and we can now build out testing for login code.

**Comment by bdmcewen** [comment]
tests created for login
