### ISSUE TITLE
Test and fix all links for any new docs, and old ones, when you switch positions

### ISSUE THREAD

**Issue by bdmcewen** [ElBowSpace/ElBowSpaceProject#27]
Make sure links in the markdown files still work I have come across some that no longer work because we restructured the file  hierarchy

**Comment by bdmcewen** [comment]
I have fixed the links in the requirements.md for milestones 1 and 2

**Comment by KevinBRitter** [comment]
Thank you, I'll tackle those in Design for milestones 1 and 2 and look at the index links

**Comment by KevinBRitter** [comment]
Leave this issue open as it will be relevant for each milestone change.

**Comment by KevinBRitter** [comment]
no longer relevant.
