### ISSUE TITLE
PostCRUDTest test_a_new_post

### ISSUE THREAD

**Issue by bdmcewen** [ElBowSpace/ElBowSpaceProject#56]
![image](https://user-images.githubusercontent.com/36974886/95911501-cd74c180-0d5e-11eb-82da-bfb64815d36c.png)

self.assertEqual(f'{post.id}', '1') falied!

**Comment by KevinBRitter** [comment]
Auto increment id numbers may be off when other tests add or delete posts.  Rewrote this to AssertTrue post.id type = int
