### ISSUE TITLE
Simple view test failures

### ISSUE THREAD

**Issue by KevinBRitter** [ElBowSpace/ElBowSpaceProject#64]
Four simple view tests are currently failing and have been commented out for debug.  Rewrite the test to reflect the changes in template structures.  And test until success!

**Comment by KevinBRitter** [comment]
This bug is caused by the url change.  Template pages no longer display their old 'name.html' in the url.  This change reflects passing data into the templates and no longer qualifies as simple views.  I've moved post and user templates into the non-crud section and they need to be reworked to success.

**Comment by KevinBRitter** [comment]
See https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing#Forms for great examples to expand the testing classes for pulling data from forms and database.

**Comment by bdmcewen** [comment]
Tests no longer needed as forms were implemented, code has evolved beyond the usage fo these tests
