### ISSUE TITLE
Use/reference to Author

### ISSUE THREAD

**Issue by bdmcewen** [ElBowSpace/ElBowSpaceProject#87]
Found several references to the author model that should not be in the code. 
 check all .md files in documentation especially design.md

found references to author or author_pk in 
url.py line 14      path('post/new_A/<int:author_pk>/', views.new_post, name='new_post'),

views.py line 97& 98             if author_pk:
                                                  post.user = User.objects.get(pk=author_pk)

register_Author .... this file should exist?

user_detail.html line 18 <p><a href="{% url 'new_post' author_pk=user.id %}">New Post</a></p>

**Comment by KevinBRitter** [comment]
author_pk is required at this time to differentiate between a general user for the method and a specific user, the one who authors the post.  It will stay until refactoring in views.py and urls.py

**Comment by KevinBRitter** [comment]
Changes to design doc have been made.  Author comments removed.
